### PR TITLE
Add test that covers #100

### PR DESCRIPTION
**Pull request by webmaster128**

### CODE REVIEW

**Comment by webmaster128** [comment]
Line 92 is the first test that fails. There we have `\"` followed by more arguments.

This is because `\"` is handled like an escaled `"` but I guess this is a very unix world view. On Windows quotes are escaped differently.

With the current behavior, [/Fo width directories](https://msdn.microsoft.com/en-us/library/yb8e9b8y.aspx) cannot be used as long as it is followed by additional arguments.

**Comment by frerich** [comment]
I'm not sure that `But the cmake command is run before any compiler call.` is true, I wouldn't be surprised if CMake actually performs various compiler invocations to test for features, e.g. the compiler version itself or header files.

**Comment by webmaster128** [comment]
I cannot reproduce the CMake problem. I tried (using Python 3)

```
pip install py2exe
python setup.py py2exe
```

This builds with warning (error?)

```
running py2exe

  2 missing Modules
  ------------------
? readline                            imported from cmd, code, pdb
? scandir                             imported from __SCRIPT__
Building 'dist\clcache.exe'.
```

Now I have a clcache.exe in C:\Users\kullo\clcache-webmaster128\dist\

```
set CC=C:\Users\kullo\clcache-webmaster128\dist\clcache.exe
set CXX=C:\Users\kullo\clcache-webmaster128\dist\clcache.exe
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%INSTALL_DIR%" -G "NMake Makefiles" "%SOURCE_DIR%" || goto error
```

This gives me

```
-- The C compiler identification is MSVC 19.0.23918.0
-- The CXX compiler identification is MSVC 19.0.23918.0
-- Check for working C compiler: C:/Users/kullo/clcache-webmaster128/dist/clcach
e.exe
-- Check for working C compiler: C:/Users/kullo/clcache-webmaster128/dist/clcach
e.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Users/kullo/clcache-webmaster128/dist/clca
che.exe
-- Check for working CXX compiler: C:/Users/kullo/clcache-webmaster128/dist/clca
che.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/kullo/workspace-playground/build-h
ttpclient-curl
```

**Comment by webmaster128** [comment]
@sowsem Could you please set CLCACHE_LOG=1 and post the output of CMakeFiles/CMakeOutput.log (as a gist). There you can find the compiler check calls and tracing output from clcache.

**Comment by sowsem** [comment]
Here it is the gist:
https://gist.github.com/sowsem/5080d43be4b32fea828a8f62cf8055ab

BTW, calling from the command line what it is inside _Invoking real compiler as _ it actually works! So it  should / may have something to do how the real compiler is being called or from where.

**Comment by frerich** [comment]
I hope that if this branch gets rebased on top of master, the test failure actually causes the CI to fail, too...

**Comment by webmaster128** [comment]
Thanks. This is a separate bug revealed by this bugfix. See #108

**Comment by webmaster128** [comment]
Sorry for not calling this WIP when it was. I consider this done now and ready for review/discussion/merge.

**Comment by frerich** [comment]
Kinda hard to review it, but the tests pass, so I guess it's okay. :-]

**Pull request merged**
