### PR TITLE
Analyze environment

### PR DESCRIPTION
**Pull request by webmaster128**
This is the first step of dealing with the `CL` and `_CL_` environment variables.

Tests are about to follow.

### CODE REVIEW

**Comment by webmaster128** [comment]
Check, I think this is it for CL and _CL_

**Comment by frerich** [comment]
I am currently on vacation without Access to my development environment, so I cannot test this: wouldn't it be easier to pass CL and _CL_ to the function which also parses response files, and then prepend resp. append the parsed argument vector to the effective command line returned by expandCommandLine?

The only complication I can think of is that the environment variables should get un-set in case clcache invokes itself for multiple source file arguments.

**Comment by webmaster128** [comment]
Sure, it is possible to implement parsing the variables. But it's not going to be easier. A lot of tests need to be written and a lot of code need to be touched potentially, since we need to keep our modified environment, which also conflicts with #192.

This just aims to ensure correctness as a short to mid-term solution until someone needs `CL` and `_CL_` working.

**Comment by webmaster128** [comment]
Closing this one as I guess it is easier to implement support for `CL` and `_CL_` than counting misses.

**Pull request closed without merging**
