### PR TITLE
Add new env variable to control clcache lock timeout. Default to old …

### PR DESCRIPTION
**Pull request by tarcisiofischer**

### CODE REVIEW

**Comment by tarcisiofischer** [comment]
Closes #25

**Comment by frerich** [comment]
Looks good! However, can you please also document it in the `README.asciidoc` file (which discusses all available environment variables)?

**Comment by webmaster128** [comment]
@tarcisiofischer knock knock

**Comment by webmaster128** [comment]
Thanks for updating this. Content looks good to me.

Please note that there are no notifications when you change a pull request, so you might want to add a comment to indicate that you're happy with your work. I just came across by accident because your PR now got a green mark from the CI.

Could you please copy the "Closes #25" into the pull request description? You can edit that. I think this is necessary for auto-closing (https://github.com/blog/1506-closing-issues-via-pull-requests).

**Comment by frerich** [comment]
Nevermind, it's no biggie to close the issue manually while mentioning this PR. Thanks!

**Pull request merged**
