### PR TITLE
Mypy: enable checks

### PR DESCRIPTION
**Pull request by xoviat**
Closes #293.

### CODE REVIEW

**Comment by xoviat** [comment]
There: no need to use hacky imports and the old comment style.

**Comment by frerich** [comment]
Ah, nice! These annotations work with Python 3.4? I must admit - I don't understand how this relates to your `setup.py` changes though. :-]

**Comment by xoviat** [comment]
>  I must admit - I don't understand how this relates to your setup.py changes though. :-]'

https://github.com/frerich/clcache/blob/05b29318a8b4f2ce8f1db2bf7ee2cc2a60d9fd25/setup.py#L17

**Comment by frerich** [comment]
Ok

**Comment by frerich** [comment]
I'm confused by which issue you want to fix here - #287 is a PR related to patching distutils. Did you maybe mean to supersede #293 ?

**Comment by xoviat** [comment]
Yes, sorry.

**Comment by frerich** [comment]
Merged, thanks!

**Pull request merged**
