### PR TITLE
Add license to tests

### PR DESCRIPTION
**Pull request by webmaster128**
This adds the same 3-clause BSD license that we have in clcache.py to tests.py.

I used the [Github generated version](https://github.com/webmaster128/github-bsd-3-clause/blob/master/LICENSE) of the license to have useful witespace and linebreaks.

Additionally I changed

> Neither the name of [repository_name] nor the names of its contributors

to

> Neither the name of the copyright holder nor the names of its contributors

which I took from https://opensource.org/licenses/BSD-3-Clause

Now the file was created by @vchigrin, so I'd like to ask you, if it is in your interest to license your work under these conditions. I you want, I can add your real name, company or email address. Just leave a comment, what you prefer.

### CODE REVIEW

**Comment by frerich** [comment]
The BSD 3-clause license is fine with me, thanks!

**Comment by webmaster128** [comment]
Fine :) But we should wait for vchigrin, who was the original author of the file.

**Comment by webmaster128** [comment]
@vchigrin, could you please have a look at this PR adding a license to clcache tests.py, you created? Thanks!

**Comment by frerich** [comment]
@vchigrin -- ping. :-)

**Comment by webmaster128** [comment]
@frerich Would you accept a PR where I delete the current tests.py entirely and add all the tests written by me, such that we can start a fresh tests file including the license header?

**Comment by frerich** [comment]
@webmaster128 Definitely! The status quo is somewhat unsatisfactory.

**Pull request closed without merging**
