### PR TITLE
Improve command line argument handling

### PR DESCRIPTION
**Pull request by webmaster128**
* use argparse library for cleaner argument parsing
* auto-generate help/usage message
* Force integer value for `-M`
* Add aliases `--show-stats`, `--zero-stats`, `--max-size` known from ccache
* Block values less or equal to 0 for `-M`

This is work in progress, which should not be merged because I found another bug that should be handled first.

### CODE REVIEW

**Comment by webmaster128** [comment]
Rebased onto current master. I am happy with this for now, but I guess there is room for comments.

**Comment by frerich** [comment]
The command line parsing is really a tricky part of `clcache.py`. There have been numerous patches back and forth affecting this. And there's still one issue open about this, #31 .

If I remember correctly, one source of complexity was the fact that the optional command file (`@foo`) is parsed with slightly different rules than what's documented on e.g. https://msdn.microsoft.com/en-us/library/17w5ykft.aspx

**Comment by frerich** [comment]
One particular case I remember which excluded using any kind of ready-made command line parsing library: an argument like `/Fo"Release\"`.

**Comment by webmaster128** [comment]
The idea here is to handle clcache arguments only. Everything else is passed into `compiler_args`.

But unfortunately, this does only work as long as cl.exe arguments do not start with `-`. Damn.

**Pull request closed without merging**
