### PR TITLE
Rename parseIncludesList() and add tests

### PR DESCRIPTION
**Pull request by webmaster128**
WIP. Let's see if this works as expected ...

### CODE REVIEW

**Comment by webmaster128** [comment]
Alright, looks like there is no bug in here. So I am happy with this now: some minor refactorings and a test.

**Comment by webmaster128** [comment]
So, I hope I got everything. Anything else?

**Comment by frerich** [comment]
The only thing left would be a glass of $FAVORITE_BEVERAGE to celebrate the merge, I guess. ;-)

**Comment by webmaster128** [comment]
Fine. $FAVORITE_BEVERAGE comes with after fixing this direct mode recompile bug, I am hunting down with all of those current PRs.

**Pull request merged**
