### PR TITLE
Make test results show up in AppVeyor web UI

### PR DESCRIPTION
**Pull request by frerich**
The idea is to make the Python unittest-based tests generate junit which
can then be fed to the appveyor UI. The little PowerShell script was
taken from

  https://www.appveyor.com/docs/running-tests#uploading-xml-test-results

### CODE REVIEW

**Comment by frerich** [comment]
https://ci.appveyor.com/project/frerich/clcache/build/1.0.240/job/6i4aj545fwx4a3he/tests shows some sample output (including two intentionally broken tests to show how error output is visualised).

**Comment by webmaster128** [comment]
Cool. This was the noisy test output from compiler calls is not too annoying anymore.

**Comment by frerich** [comment]
Yeah. Alas, merging this will conflict with #92 . :-/

**Comment by webmaster128** [comment]
No problem, this is a trivial merge. I'll rebase onto master as soon as this one is in.

**Pull request merged**
