### PR TITLE
Extract CompilerArtifactsRepository from Cache

### PR DESCRIPTION
**Pull request by webmaster128**
this doe not change any functionality

### CODE REVIEW

**Comment by webmaster128** [comment]
Check, rebased. This is a big change bit it is just moving around existing code.

**Comment by frerich** [comment]
A lot of diff, but it seems straightforward. Thanks! Do you plan to do more refactorings according to the ideas discussed in #187 ? Just so that we don't step on each others toes, this stuff is bound to cause merge conflicts.

**Comment by webmaster128** [comment]
I can do all of the renaming if there is no time pressure. I somehow like this cleanup stuff when the brain is already fucked. It's a bit meditative.

**Comment by frerich** [comment]
Sure, go ahead. And indeed, I think a straightforward (but not totally trivial) refactoring if you have a clear plan definitely has a meditative effect.

**Pull request merged**
