### PR TITLE
Add initial compile tests

### PR DESCRIPTION
**Pull request by webmaster128**
This is a basic version of testing the compilation through clcache, starting with a simple C and a simple Cpp program.

I need the CI to work on that. Feel free to comment at any point but please don't merge. I'll add a comment when I am done.

### CODE REVIEW

**Comment by frerich** [comment]
The man after which the famous sequence is named was called Fibonacci. ;-)

**Comment by webmaster128** [comment]
Good point, thanks

**Comment by webmaster128** [comment]
Okay, I am happy with this for now. This already covers a lot of additional clcache codepaths. Next project would be to test for cache hits, but that is another topic.

**Comment by frerich** [comment]
Thanks, this looks interesting! A couple of questions:

1. Can you please mention (in the commit log message) why you added 'python clcache.py -s' as an after-test step)?
2. I think it would be nice to make the tests perform some 'tear down', too - they should at least delete any generated files (e.g. .obj and .exe files), no?
3. Instead of assuming that `python` is in the Path, it seems to me that using `sys.executable` would be better (this gives the path to the current Python interpreter). I suspect that this will fix running the tests when not having `python` in the path.

**Comment by frerich** [comment]
Also, I wonder - are there any nice code coverage solutions for Python? I suppose ti would be good to set that up early to be able to tell what needs testing and whether any two tests have significant overlap.

**Comment by webmaster128** [comment]
Alright:

1. I added a comment in the config file itself to make that clear for any future reader.
2. Best practice is to leave test artefacts untouchted in order to be able to better debug testing. But it might be useful to have a specific test output directory the can be gitignored. I'd leave it as it is now and find a solution that works well when more artefacts are added into the mix.
3. Good point, applied

> Also, I wonder - are there any nice code coverage solutions for Python?

I don't know of any but I am not a Python expert. For now I see a lot of low hanging fruits and existing bugs that can be tested away before we really need coverage.

**Pull request merged**
