### PR TITLE
Cleanup AppVeyor config

### PR DESCRIPTION
**Pull request by webmaster128**
Minor adjustments to make AppVeyor just a little bit nicer to read

### CODE REVIEW

**Comment by frerich** [comment]
Why did you convert the line endings? The version in the repository should always use Unix line endings, Git will then take care of converting to Windows line endings when checking it and back to Unix line endings when committing via the `core.autocrlf` setting.

**Comment by webmaster128** [comment]
I tried to fix the issue that multiple lines in the .yml file ended up as one command. But it turns out this is not caused by line endings. So I can remove the commit.

Good to know (UNIX line endings). I occasionally checked in files with Windows line endings. So I'll pick up this policy.

I have `core.autocrlf` set to `false` but that is no big deal since I can use alternative Editors on Windows that work with `"\n"`

**Comment by webmaster128** [comment]
Ah got it, the YAML block style was the cause :) All green here and Windows line endings reverted.

**Comment by frerich** [comment]
Looks good, merged. Thanks!

**Pull request merged**
