### PR TITLE
Fix /Fo handling for quoted values

### LINKED ISSUE #108: Cannot open compiler generated file: '"Debug\\".obj' with double backslash in the path
User @sowsem found this error when compiling with `/Fo"Debug\\" `:

```
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"Debug\\" /Fd"Debug\vc120.pdb" /Gd /TC /analyze- /errorReport:queue CMakeCCompilerId.c
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\clcache.py Found real compiler binary at 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl_real.exe'
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\clcache.py Parsing given commandline '['@C:\\Users\\davido\\AppData\\Local\\Temp\\tmpf22c581ab5514910a81a2a62e85395c1.rsp']'
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\clcache.py Expanded commandline '[u'/c', u'/nologo', u'/W0', u'/WX-', u'/Od', u'/Oy-', u'/D', u'_MBCS', u'/Gm-', u'/EHsc', u'/RTC1', u'/MDd', u'/GS', u'/fp:precise', u'/Zc:wchar_t', u'/Zc:forScope', u'/Fo"Debug\\\\"', u'/Fd"Debug\\vc120.pdb"', u'/Gd', u'/TC', u'/analyze-', u'/errorReport:queue', u'CMakeCCompilerId.c']'
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\clcache.py Compiler output file: 'Debug\\'
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\clcache.py Invoking real compiler as 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl_real.exe /showIncludes /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"Debug\\" /Fd"Debug\vc120.pdb" /Gd /TC /analyze- /errorReport:queue CMakeCCompilerId.c'
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\clcache.py Real compiler returned code 1
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\clcache.py Finished. Exit code 1
  CMakeCCompilerId.c
C:\dev\projects\projectx-client\projects\projectx_win_tests\CMakeFiles\3.4.3\CompilerIdC\CMakeCCompilerId.c : fatal error C1083: Cannot open compiler generated file: '"Debug\\".obj': Invalid argument [C:\dev\projects\projectx-client\projects\projectx_win_tests\CMakeFiles\3.4.3\CompilerIdC\CompilerIdC.vcxproj]
```

from https://gist.github.com/sowsem/5080d43be4b32fea828a8f62cf8055ab

This revealed by a change in #105. The actual bug is that 

```
        # Strip quotes around file names; seems to happen with source files
        # with spaces in their names specified via a response file generated
        # by Visual Studio.
        if outputFile.startswith('"') and outputFile.endswith('"'):
            outputFile = outputFile[1:-1]
```

does not happen in the correct code branch in analyzeCommandLine(). So `/Fo"Debug\\"` does not become output file `Debug\CMakeCCompilerId.obj` but `"Debug\"`.

### PR DESCRIPTION
**Pull request by webmaster128**
I think this fixes #108

### CODE REVIEW

**Comment by webmaster128** [comment]
As soon as I get feedback from @sowsem, I'll add a changelog entry for this.

**Comment by webmaster128** [comment]
Much better than before.

Could you verify if this real compiller command line works? Note that there are two backslashes after Debug

```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl_real.exe /showIncludes /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"Debug\\" /Fd"Debug\vc120.pdb" /Gd /TC /analyze- /errorReport:queue CMakeCCompilerId.c
```

**Comment by frerich** [comment]
Indeed, the expanded command line looks a lot more sensible now!

**Comment by sowsem** [comment]
Yes, it works. From cygwin:

`davido@DAVIDE1C /cygdrive/c/dev/projects/projectx-client/projects/projectx_win_tests/CMakeFiles/3.4.3/CompilerIdC
$ "/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl_real.exe" /showIncludes /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"Debug\\" /Fd"Debug\vc120.pdb" /Gd /TC /analyze- /errorReport:queue CMakeCCompilerId.c`
`CMakeCCompilerId.c`

Same if I run it from the cmd:

C:\dev\projects\projectx-client\projects\projectx_win_tests\CMakeFiles\3.4.3\CompilerIdC
>"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl_real.exe" /showI
ncludes /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:prec
ise /Zc:wchar_t /Zc:forScope /Fo"Debug\\" /Fd"Debug\vc120.pdb" /Gd /TC /analyze-
 /errorReport:queue CMakeCCompilerId.c
`CMakeCCompilerId.c`

**Comment by webmaster128** [comment]
The remaining issue is that `\\` is handled differently when using a shell or not:

1. cmd: `"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe" /c /Fo"Debug\\" CMakeCCompilerId.c` :ok:
2. Python: `subprocess.check_call([r'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe', r'/c', r'/Fo"Debug\\"', r'CMakeCCompilerId.c'])` :x:
3. Python `subprocess.check_call(r'"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe" /c /Fo"Debug\\" CMakeCCompilerId.c', shell=True)` :ok:

What can we do?

* `/Fo"Debug\\" ` in a cmd shell works with cl.exe (is this a bug?)
* `/Fo"Debug\\" ` in a direct process call with cl.exe is invalid input
* `/Fo"Debug\\" ` is received unchanged by clcache via shell

Now we can either call the real compiler via shell=True or try to fiddle around with changing arguments.

But isn't the real question why we have two backslashes as input parameter?

**Comment by webmaster128** [comment]
Just FYI: in blockquotes, Github converts double backslashes into a single backslash. This does not happen for code formatting.

**Comment by frerich** [comment]
I think it's important here to not minimise the test cases too much: in #108, @sowsem wrote

{quote}
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\clcache.py Found real compiler binary at 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl_real.exe'
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\clcache.py Parsing given commandline '['@C:\\Users\\davido\\AppData\\Local\\Temp\\tmpf22c581ab5514910a81a2a62e85395c1.rsp']'
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\clcache.py Expanded commandline '[u'/c', u'/nologo', u'/W0', u'/WX-', u'/Od', u'/Oy-', u'/D', u'_MBCS', u'/Gm-', u'/EHsc', u'/RTC1', u'/MDd', u'/GS', u'/fp:precise', u'/Zc:wchar_t', u'/Zc:forScope', u'/Fo"Debug\\\\"', u'/Fd"Debug\\vc120.pdb"', u'/Gd', u'/TC', u'/analyze-', u'/errorReport:queue', u'CMakeCCompilerId.c']'
 {quote}

Note how /Fo is not specified in the command line at all - it's read from the response file, for which wildly different escape rules may apply.

**Comment by frerich** [comment]
I can reproduce this behaviour with a carefully crafted response file. Given

f.c:
```
void f() {}
```

response.rsp:
```
/c /Fo"Debug\\" f.c
```

I see
```
C:\Users\Frerich\src\clcache\issues\108>cl @response.rsp
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl /c /Fo"Debug\\" f.c


f.c
```

...but clcache prints:
```
C:\Users\Frerich\src\clcache\issues\108>C:\Users\Frerich\binpackage\python\x86\2.7.10binary\python.exe C:\Users\Frerich\src\clcache\clcache.py @response.rsp
C:\Users\Frerich\src\clcache\clcache.py Found real compiler binary at 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\cl.exe'
C:\Users\Frerich\src\clcache\clcache.py Parsing given commandline '['@response.rsp']'
C:\Users\Frerich\src\clcache\clcache.py Expanded commandline '[u'/c', u'/Fo"Debug\\\\"', u'f.c']'
C:\Users\Frerich\src\clcache\clcache.py Compiler output file: 'Debug\'
C:\Users\Frerich\src\clcache\clcache.py Invoking real compiler as [u'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\BIN\\cl.exe', u'/showIncludes',
u'/c', u'/Fo"Debug\\\\"', u'f.c']
```
The expanded command line -- and thus the command line printed to the real compiler -- seems wrong to me.

**Comment by frerich** [comment]
Sorry, that was silly - I forgot that we're printing the string representations of Python lists, thus the backslashes are duplicated. Oops!

**Comment by webmaster128** [comment]
> it's read from the response file, for which wildly different escape rules may apply.

Good point. Maybe we can find something about that.

**Comment by frerich** [comment]
By now, I wonder whether the response file is parsed according to the exact same rules which apply to parsing Windows command lines...

**Comment by frerich** [comment]
Interesting code: the LLVM command line parser which also features a function for expanding response files (and they have their own tokenizer).

**Comment by frerich** [comment]
First impression of the llvm code:

1. [`llvm:libDriverMain`](http://llvm.org/docs/doxygen/html/LibDriver_8cpp_source.html#l00102) calls [`cl::ExpandResponseFiles`](http://llvm.org/docs/doxygen/html/CommandLine_8cpp_source.html#l00735) on the argument vector, passing [`cl::TokenizeWindowsCommandLine`](http://llvm.org/docs/doxygen/html/CommandLine_8cpp_source.html#l00618) as the argument.
2. [`cl::ExpandResponseFiles`](http://llvm.org/docs/doxygen/html/CommandLine_8cpp_source.html#l00735) repeatedly expands all `@...` arguments by calling [`cl::ExpandResponseFile`](http://llvm.org/docs/doxygen/html/CommandLine_8cpp_source.html#l00702), passing on the `Tokenizer` argument.
3. [`cl::ExpandResponseFile`](http://llvm.org/docs/doxygen/html/CommandLine_8cpp_source.html#l00702) checks a given response file for a potential UTF-16 BOM (if so, it reencodes to UTF-8) or UTF-8 BOM (which is just skipped) and then applies the given `Tokenizer` (i.e. [`cl::TokenizeWindowsCommandLine`](http://llvm.org/docs/doxygen/html/CommandLine_8cpp_source.html#l00618)) to the file contents.

Hence, it seems that all parsing logic for response files is encoded in the `TokenizeWindowsCommandLine` function, [which is documented](http://llvm.org/docs/doxygen/html/namespacellvm_1_1cl.html#a3b42fd69f84c0ceef44857e925613ee4) to implement the [quoting rules documented by Microsoft](https://msdn.microsoft.com/en-us/library/windows/desktop/17w5ykft(v=vs.85).aspx). I wonder why they didn't just use [`CommandLineToArgvW`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776391(v=vs.85).aspx), there are probably subtle differences in parsing?

In any case, I guess we could use the same logic. We're mostly there actually, we'd just need to implement `splitCommandsFile` in terms of the rules specified by Microsoft.

**Comment by webmaster128** [comment]
I think we should continue the research in #108. This PR already fixes a lot of cases, that did not work before. I just added a changelog line, so I think this can be merged.

**Comment by frerich** [comment]
Maybe. After reading up on this topic a bit more, I'm not totally sure anymore that all the existing tests make sense. For what it's worth, I decided to see what happens if I port the [`cl::TokenizeWindowsCommandLine`](http://llvm.org/docs/doxygen/html/CommandLine_8cpp_source.html#l00618) function. The [Python version I wrote](https://gist.github.com/frerich/eeb8ffc03a8dfd4750f96b35145efc3a) seems straightforward and permits defining `splitCommandsFile` as just

```python
def splitCommandsFile(content):
    tokenizer = CommandLineTokenizer(content)
    return [extractArgument(arg) for arg in tokenizer.argv]
```

However, this makes a lot of tests fail - but in interesting ways:

* Quotes are in many places dropped while parsing. I actually kinda like this, e.g. all of `/Foblah`, `"/Fooblah"`, `/Fo"blah"` and `"/Fo"blah""` seem to get parsed to `/Foblah`.

* The `testBackslashBeforeQuote` test checks what happens if there is a single backslash before a double quote, but that quote is actually not part of the argument but rather denotes the end of a string. If I read [Parsing C++ Command-Line Arguments](https://msdn.microsoft.com/en-us/library/17w5ykft.aspx) correctly, shouldn't this test actually use two backslashes at the end?

I may have ported the code wrongly, or maybe the existing tests actually are defective, or both. Anyway, I really need to get some sleep before working on this kind of stuff. Will continue later - maybe you find something interesting?

**Comment by hubx** [comment]
Hi I have a similiar setup, I tested #116 and unfortunately it only partly solves the issue. output file is correctly set, but it looks there are duplicate \\ in the cmdline to the real compiler

````
C:\path\to\clcache.py Found real compiler binary at 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe'
C:\path\to\clcache.py Expanded commandline '['/c', '/IC:\\path\\to\\code\\external\\lib\\include', '/nologo', '/W4', '/WX-', '/MP', '/O2', '/Oy-', '/D', 'NDEBUG', '/D', 'NVALGRIND', '/D', '_USE_MATH_DEFINES', '/D', 'UNICODE', '/D', '_UNICODE', '/D', 'BOOST_ALL_NO_LIB', '/D', 'CMAKE_INTDIR=\\"Release\\"', '/D', '_UNICODE', '/D', 'UNICODE', '/Gm-', '/MT', '/GS', '/fp:precise', '/Zc:wchar_t', '/Zc:forScope', '/Fo"lib.dir\\Release\\\\"', '/Fd"lib.dir\\Release\\vc120.pdb"', '/Gd', '/TP', '/analyze-', '/errorReport:queue', '/bigobj', 'C:\\path\\to\\code\\\external\\lib\\lib.cpp']'
C:\path\to\clcache.py Compiler output file: 'lib.dir\Release\lib.obj'
C:\path\to\clcache.py Invoking real compiler as ['C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin\\cl.exe', '/showIncludes', '/c', '/IC:\\path\\to\\code\\external\\lib\\include', '/nologo', '/W4', '/WX-', '/MP', '/O2', '/Oy-', '/D', 'NDEBUG', '/D', 'NVALGRIND', '/D', '_USE_MATH_DEFINES', '/D', 'UNICODE', '/D', '_UNICODE', '/D', 'BOOST_ALL_NO_LIB', '/D', 'CMAKE_INTDIR=\\"Release\\"', '/D', '_UNICODE', '/D', 'UNICODE', '/Gm-', '/MT', '/GS', '/fp:precise', '/Zc:wchar_t', '/Zc:forScope', '/Fo"lib.dir\\Release\\\\"', '/Fd"lib.dir\\Release\\vc120.pdb"', '/Gd', '/TP', '/analyze-', '/errorReport:queue', '/bigobj', 'C:\\path\\to\\code\\\external\\lib\\lib.cpp']
C:\path\to\clcache.py Real compiler returned code 1
C:\path\to\clcache.py Finished. Exit code 1
         lib.cpp
    90>C:\path\to\code\\external\lib\lib.cpp : fatal error C1083: Cannot open compiler generated file: '"lib.dir\Release\\".obj': Invalid argument...
````

I'm not sure where the escaped \ come from, is this a presentation issue of the command line arguements (threating raw strings as normal string when passing it to the cmdline?). Any hints on where I could further for this?

I also tried CommandLineTokenizer by @frerich. It works after replacing (a / with a  // in python3). But I'm not sure if this was intentional :).
````
C:\path\to\\clcache.py Found real compiler binary at 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe'
C:\path\to\\clcache.py Parsing given commandline '['@C:\\Users\\hesse\\AppData\\Local\\Temp\\tmp6e33f33e7d16472988f4447690312ffc.rsp']'
C:\path\to\\clcache.py Expanded commandline '['/c', '/IC:\\Users\\hesse\\code\\dal\\external\\lib\\include', '/nologo', '/W4', '/WX-', '/MP', '/O2', '/Oy-', '/D', 'NDEBUG', '/D', 'NVALGRIND', '/D', '_USE_MATH_DEFINES', '/D', 'UNICODE', '/D', '_UNICODE', '/D', 'BOOST_ALL_NO_LIB', '/D', 'CMAKE_INTDIR="Release"', '/D', '_UNICODE', '/D', 'UNICODE', '/Gm-', '/MT', '/GS', '/fp:precise', '/Zc:wchar_t', '/Zc:forScope', '/Folib.dir\\Release\\', '/Fdlib.dir\\Release\\vc120.pdb', '/Gd', '/TP', '/analyze-', '/errorReport:queue', '/bigobj', 'C:\\Users\\hesse\\code\\dal\\external\\lib\\lib.cpp']'
C:\path\to\\clcache.py Compiler output file: 'lib.dir\Release\lib.obj'
C:\path\to\\clcache.py Invoking real compiler as ['C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin\\cl.exe', '/showIncludes', '/c', '/IC:\\Users\\hesse\\code\\dal\\external\\lib\\include', '/nologo', '/W4', '/WX-', '/MP', '/O2', '/Oy-', '/D', 'NDEBUG', '/D', 'NVALGRIND', '/D', '_USE_MATH_DEFINES', '/D', 'UNICODE', '/D', '_UNICODE', '/D', 'BOOST_ALL_NO_LIB', '/D', 'CMAKE_INTDIR="Release"', '/D', '_UNICODE', '/D', 'UNICODE', '/Gm-', '/MT', '/GS', '/fp:precise', '/Zc:wchar_t', '/Zc:forScope', '/Folib.dir\\Release\\', '/Fdlib.dir\\Release\\vc120.pdb', '/Gd', '/TP', '/analyze-', '/errorReport:queue', '/bigobj', 'C:\\Users\\hesse\\code\\dal\\external\\lib\\lib.cpp']
C:\path\to\\clcache.py Real compiler returned code 0
C:\path\to\\clcache.py Adding file lib.dir\Release\lib.obj to cache using key 775539e41213238b2ddf29566434b34c
C:\path\to\\clcache.py Finished. Exit code 0
````

Thanks for all your work, I would really love to try this one further :)

**Comment by webmaster128** [comment]
The link @frerich found changes everything: https://msdn.microsoft.com/en-us/library/17w5ykft.aspx

I did not know about this document before, and it basically says: cl handles command line arguments differently than the default Windows shell (e.g. `echo \"` or `echo \\` contains no escaping). This is going to lead to a bunch of test changes and hopefully a better implementation.

**Comment by webmaster128** [comment]
I'd call this on hold until the command line parsing is understood better and fixed.

**Comment by frerich** [comment]
I tend to agree. I believe we first have to get a better understanding of where we want to go before we can review code to get us there. ;-)

**Comment by webmaster128** [comment]
Yes, especially because this (argument analysis) is a step 2 that build on top of a currently broken step 1 (parsing command line string into arguments list).

From what I read in the Microsoft documentation, there should not be any `_unquote()` necessary in the analysis. Arguments must come in as `/FoThe Out File.obj` from the splitting no matter how the input has been quoted.

**Comment by frerich** [comment]
For what it's worth, I just pushed an 'llvm_commandline_tokenizer' branch to the repository which ports the file parsing to the `CommandLineTokenizer` class I sketched. It also cherry-picks the test you proposed in #121 - and the test passes!

Most of the other tests fail though, but I'm tempted to claim that their expectation is actually wrong.

**Comment by webmaster128** [comment]
Could you open a PR for that branch to make it visible and allow a more specific discussion?

**Comment by frerich** [comment]
Sure. Say hello to PR #122 .

**Comment by webmaster128** [comment]
Closing for now this as it mainly contains noisy discussion about command line splitting

**Pull request closed without merging**
