### PR TITLE
Add test for changes in header

### PR DESCRIPTION
**Pull request by webmaster128**
This is WIP. We discovered that in direct mode, changing header files are not detected properly. Let's find out what is going on here.

### CODE REVIEW

**Comment by frerich** [comment]
I'm curious: who is 'we'? I'm always interested in hearing about use cases for clcache. :-)

**Comment by webmaster128** [comment]
We are [Kullo – Secure Communication](https://www.kullo.net/)

**Comment by webmaster128** [comment]
Okay I found the bug by reviewing the code. I'll update this until I have a test setup to cover the bug and fix it then.

**Comment by frerich** [comment]
Thanks!

**Pull request merged**
